# Generated by Django 5.1.1 on 2024-09-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='note',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
