# Generated by Django 5.1.1 on 2024-09-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_rename_name_note_password_alter_note_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='password',
            new_name='name',
        ),
    ]
